[build]
jobs = 8

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
opt-level = 0
debug = false

[profile.dev.package."*"]
opt-level = 0

[profile.release]
lto = "thin"
codegen-units = 16
strip = true
opt-level = "s"
